use super::*;

use lombok_macros::{Data, New};
/// The four phases of a transition lifecycle.
///
/// Lifecycle: `Exited` → `Entering` → `Entered` →
/// `Exiting` → `Exited` (looping back). The state
/// machine is symmetric on the way in and out — the
/// `Entering` and `Exiting` phases both have a `progress`
/// value in `(0.0, 1.0)`, while `Entered` and `Exited`
/// are terminal resting states (`progress` pinned to
/// `1.0` and `0.0` respectively).
///
/// Phases are public and `Clone + Copy + PartialEq` so
/// consumers can write `match phase { ... }` and dispatch
/// on them without going through the signal indirection
/// every time.
///
/// Note: not deriving `Data` / `New` from lombok because
/// both `Data` and `New` derive macros are only
/// supported for structs (see `UNSUPPORTED_DATA_DERIVE`
/// in lombok-macros 2.0.36). The standard library
/// derives below are sufficient — we don't need
/// getters/setters on the variants.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum TransitionPhase {
    /// The element is not yet on-screen (initial state).
    /// `progress` is `0.0`.
    Exited,
    /// The element is animating in. `progress` rises from
    /// `0.0` toward `1.0` as `tick(elapsed_ms)` is called.
    Entering,
    /// The element is fully on-screen. `progress` is
    /// `1.0`.
    Entered,
    /// The element is animating out. `progress` falls from
    /// `1.0` toward `0.0` as `tick(elapsed_ms)` is called.
    Exiting,
}

impl TransitionPhase {
    /// Returns a fresh `TransitionPhase` value of
    /// `Exited`. Convenience for `Signal::create` call
    /// sites.
    pub const fn exited() -> Self {
        TransitionPhase::Exited
    }
}

/// Configuration for a `TransitionState`.
///
/// Both fields are reactive (the underlying state holds a
/// `Signal<TransitionConfig>`), so consumers can adjust
/// the durations at runtime via `change_config` and any
/// pending timers driven by the old config will continue
/// using the old values until they next read the config
/// signal.
#[derive(Clone, Copy, Data, Debug, Eq, PartialEq)]
pub struct TransitionConfig {
    /// The duration of the enter animation, in
    /// milliseconds.
    #[get(type(copy))]
    pub enter_ms: u32,
    /// The duration of the exit animation, in
    /// milliseconds.
    #[get(type(copy))]
    pub exit_ms: u32,
}

impl TransitionConfig {
    /// Returns a config with both enter and exit durations
    /// set to `ms`.
    ///
    /// Named `with_ms` (not `new`) to avoid colliding
    /// with the `new` constructor generated by
    /// `#[derive(New)]`. (We don't derive `New` here
    /// because the field name `enter_ms` would generate
    /// a `set_enter_ms` setter that nobody asked for —
    /// keeping the struct `Copy` and writing it via
    /// `TransitionConfig { enter_ms, exit_ms }` is
    /// simpler.)
    pub const fn with_ms(ms: u32) -> Self {
        Self {
            enter_ms: ms,
            exit_ms: ms,
        }
    }

    /// Returns a config with separate enter and exit
    /// durations. See `with_ms` for the naming note.
    pub const fn with_durations(enter_ms: u32, exit_ms: u32) -> Self {
        Self { enter_ms, exit_ms }
    }

    /// Returns the duration (in ms) corresponding to the
    /// given phase. Returns `0` for terminal phases
    /// (`Entered`, `Exited`) — these don't tick.
    pub fn duration_for(&self, phase: TransitionPhase) -> u32 {
        match phase {
            TransitionPhase::Entering => self.enter_ms,
            TransitionPhase::Exiting => self.exit_ms,
            TransitionPhase::Entered | TransitionPhase::Exited => 0,
        }
    }
}

impl Default for TransitionConfig {
    fn default() -> Self {
        // Matches the CSS defaults used elsewhere in
        // euv-ui (var!(duration-normal) ≈ 200ms).
        Self::with_ms(200)
    }
}

/// The aggregate transition state.
///
/// Constructed once per animated element via
/// `App::use_transition(...)`. Cheap to `Clone` (each
/// internal signal is `Copy`-by-pointer). Drives the
/// state machine forward via `tick(elapsed_ms)` and
/// exposes the current phase / progress as reactive
/// signals so the consuming component's render closure
/// re-runs whenever either changes.
#[derive(Clone, Data, New)]
pub struct TransitionState {
    /// The current lifecycle phase.
    phase: Signal<TransitionPhase>,
    /// The current progress, in `[0.0, 1.0]`. Pinned to
    /// `1.0` for `Entered`, `0.0` for `Exited`, and
    /// intermediate for `Entering` / `Exiting`.
    progress: Signal<f64>,
    /// The duration config (see `TransitionConfig`).
    config: Signal<TransitionConfig>,
}

impl TransitionState {
    /// Returns a `Signal<TransitionPhase>` clone of the
    /// current phase.
    pub fn phase(&self) -> Signal<TransitionPhase> {
        self.phase
    }

    /// Returns a `Signal<f64>` clone of the current
    /// progress.
    pub fn progress(&self) -> Signal<f64> {
        self.progress
    }

    /// Returns a `Signal<TransitionConfig>` clone of the
    /// current config.
    pub fn config(&self) -> Signal<TransitionConfig> {
        self.config
    }

    /// Returns the current phase as a snapshot value.
    pub fn current_phase(&self) -> TransitionPhase {
        self.phase.get()
    }

    /// Returns the current progress as a snapshot value.
    pub fn current_progress(&self) -> f64 {
        self.progress.get()
    }

    /// Returns the current config as a snapshot value.
    pub fn current_config(&self) -> TransitionConfig {
        self.config.get()
    }

    /// Returns `true` if the element is currently
    /// animating (i.e. `Entering` or `Exiting`).
    pub fn is_animating(&self) -> bool {
        matches!(
            self.phase.get(),
            TransitionPhase::Entering | TransitionPhase::Exiting
        )
    }

    /// Returns `true` if the element is fully on-screen
    /// (`Entered`).
    pub fn is_entered(&self) -> bool {
        self.phase.get() == TransitionPhase::Entered
    }

    /// Returns `true` if the element is fully off-screen
    /// (`Exited`).
    pub fn is_exited(&self) -> bool {
        self.phase.get() == TransitionPhase::Exited
    }

    /// Replaces the duration config.
    ///
    /// Named `change_config` (not `set_config`) to avoid
    /// colliding with the `set_config` setter generated
    /// by `#[derive(Data)]` on the struct field.
    pub fn change_config(&self, config: TransitionConfig) {
        self.config.set(config);
    }

    /// Starts the enter animation. Sets the phase to
    /// `Entering` and resets progress to `0.0`. No-op if
    /// the transition is already in `Entering` / `Entered`.
    pub fn enter(&self) {
        let current: TransitionPhase = self.phase.get();
        if matches!(
            current,
            TransitionPhase::Entering | TransitionPhase::Entered
        ) {
            return;
        }
        self.phase.set(TransitionPhase::Entering);
        self.progress.set(0.0);
    }

    /// Starts the exit animation. Sets the phase to
    /// `Exiting` and starts progress from `1.0`. No-op if
    /// the transition is already in `Exiting` / `Exited`.
    pub fn exit(&self) {
        let current: TransitionPhase = self.phase.get();
        if matches!(current, TransitionPhase::Exiting | TransitionPhase::Exited) {
            return;
        }
        self.phase.set(TransitionPhase::Exiting);
        self.progress.set(1.0);
    }

    /// Toggles between `Entered` and `Exited`. Equivalent
    /// to `enter()` if currently `Exiting` / `Exited`,
    /// and `exit()` if currently `Entering` / `Entered`.
    pub fn toggle(&self) {
        match self.phase.get() {
            TransitionPhase::Entered | TransitionPhase::Entering => {
                self.exit();
            }
            TransitionPhase::Exiting | TransitionPhase::Exited => {
                self.enter();
            }
        }
    }

    /// Advances the transition by `elapsed_ms`
    /// milliseconds. Updates `progress` and, if the
    /// transition has reached its end, advances the phase
    /// to the corresponding terminal phase (`Entered` or
    /// `Exited`).
    ///
    /// This is the primitive the consumer drives from a
    /// `setInterval` or `requestAnimationFrame` loop. The
    /// state itself does NOT spawn a timer — that would
    /// require `wasm_bindgen_futures::spawn_local` and
    /// would prevent the primitive from being usable on
    /// native targets. Instead, the consumer is expected
    /// to wire up the timer (see the docs on
    /// `tick_until_done` for a helper that drives `tick`
    /// in a loop).
    ///
    /// # Arguments
    ///
    /// - `u32` - The number of milliseconds that have
    ///   elapsed since the last `tick` call. Must be
    ///   non-negative. The state does not validate this;
    ///   passing `0` is a no-op, passing a value larger
    ///   than the remaining duration jumps directly to
    ///   the terminal phase.
    pub fn tick(&self, elapsed_ms: u32) {
        match self.phase.get() {
            TransitionPhase::Exited | TransitionPhase::Entered => {
                // Terminal phases don't tick.
            }
            TransitionPhase::Entering => {
                let total: u32 = self.config.get().enter_ms;
                let current: f64 = self.progress.get();
                if total == 0 {
                    // Zero-duration enter jumps straight
                    // to `Entered`.
                    self.progress.set(1.0);
                    self.phase.set(TransitionPhase::Entered);
                    return;
                }
                let next: f64 = current + (elapsed_ms as f64) / (total as f64);
                if next >= 1.0 {
                    self.progress.set(1.0);
                    self.phase.set(TransitionPhase::Entered);
                } else {
                    self.progress.set(next);
                }
            }
            TransitionPhase::Exiting => {
                let total: u32 = self.config.get().exit_ms;
                let current: f64 = self.progress.get();
                if total == 0 {
                    self.progress.set(0.0);
                    self.phase.set(TransitionPhase::Exited);
                    return;
                }
                let next: f64 = current - (elapsed_ms as f64) / (total as f64);
                if next <= 0.0 {
                    self.progress.set(0.0);
                    self.phase.set(TransitionPhase::Exited);
                } else {
                    self.progress.set(next);
                }
            }
        }
    }

    /// Drives `tick` until the transition reaches a
    /// terminal phase (`Entered` or `Exited`), using
    /// `step_ms` as the per-tick delta.
    ///
    /// Useful for tests and for native builds that want
    /// to fast-forward a transition synchronously. On
    /// wasm the consumer should NOT use this — instead
    /// drive `tick` from a real timer loop and render
    /// each frame.
    ///
    /// # Arguments
    ///
    /// - `u32` - The per-tick delta, in milliseconds.
    ///   Typical value is `16` (≈60 fps).
    pub fn tick_until_done(&self, step_ms: u32) {
        while self.is_animating() {
            self.tick(step_ms);
        }
    }

    /// Resets the transition back to the `Exited` state
    /// (progress = `0.0`). Cancels any in-flight
    /// animation immediately. Useful for "the user
    /// closed the dialog before the exit animation
    /// finished, force-reset" flows.
    pub fn reset(&self) {
        self.phase.set(TransitionPhase::Exited);
        self.progress.set(0.0);
    }

    /// Returns the time remaining (in ms) until the
    /// current transition completes. Returns `0` for
    /// terminal phases.
    pub fn remaining_ms(&self) -> u32 {
        match self.phase.get() {
            TransitionPhase::Exited | TransitionPhase::Entered => 0,
            TransitionPhase::Entering => {
                let total: u32 = self.config.get().enter_ms;
                let current: f64 = self.progress.get() * total as f64;
                (total as f64 - current).max(0.0) as u32
            }
            TransitionPhase::Exiting => {
                let total: u32 = self.config.get().exit_ms;
                let current: f64 = self.progress.get() * total as f64;
                current as u32
            }
        }
    }
}
