use super::*;

use crate::Signal;
use lombok_macros::{Data, New};
use std::collections::HashMap;
/// The aggregate i18n state.
///
/// Constructed once per app via `App::use_i18n()`, threaded
/// through any code that needs to render translated text.
/// Cheap to `Clone` (the internal signal is
/// `Copy`-by-pointer).
///
/// # Storage
///
/// Messages are stored in a `Signal<HashMap<String,
/// HashMap<String, String>>>` keyed by `locale → (key →
/// message)`. The map is intentionally two-level: it
/// matches how translation files are typically organized
/// (`en.json` is one flat key/value map, `zh-CN.json` is
/// another, etc.) and it lets `add_messages(locale,
/// &[(k, v), ...])` build the inner map by direct
/// insertion without the user having to allocate one
/// `HashMap` per locale.
#[derive(Clone, Data, New)]
pub struct I18n {
    /// The currently-active locale tag. Setting this
    /// via `set_locale` triggers a reactive update that
    /// re-evaluates any reactive `t(...)` read.
    locale: Signal<String>,
    /// The locale to fall back to when a key is missing
    /// in the active locale. Defaults to `"en"`.
    fallback_locale: Signal<String>,
    /// The full translation table. The outer key is the
    /// locale tag, the inner key is the message key, the
    /// inner value is the (optionally placeholder-
    /// containing) message.
    messages: Signal<HashMap<String, HashMap<String, String>>>,
}

/// An entry for `I18n::add_messages` — a `(key, value)`
/// pair that the caller usually writes as a single
/// literal array. The tuple form keeps the public API
/// allocation-free for the common "compile-time literal
/// list of pairs" case.
pub type MessageEntry = (&'static str, &'static str);

impl I18n {
    /// Returns a `Signal<String>` clone of the active
    /// locale. Read with `.get()` inside a render closure
    /// to subscribe to locale changes.
    pub fn locale(&self) -> Signal<String> {
        self.locale
    }

    /// Returns a `Signal<String>` clone of the fallback
    /// locale.
    pub fn fallback_locale(&self) -> Signal<String> {
        self.fallback_locale
    }

    /// Sets the active locale to `locale`. Triggers a
    /// reactive update so any reactive `t(key)` read
    /// re-evaluates.
    ///
    /// Named `change_locale` (not `set_locale`) to avoid
    /// colliding with the `set_locale` getter generated by
    /// `#[derive(Data)]` on the struct field.
    pub fn change_locale(&self, locale: &str) {
        self.locale.set(locale.to_string());
    }

    /// Sets the fallback locale. Trigger a reactive
    /// update for any `t(key)` whose key is missing in
    /// the active locale — they may now resolve to a
    /// different fallback value.
    ///
    /// Named `change_fallback_locale` (not
    /// `set_fallback_locale`) for the same reason as
    /// `change_locale`.
    pub fn change_fallback_locale(&self, locale: &str) {
        self.fallback_locale.set(locale.to_string());
    }

    /// Adds a batch of `(key, message)` entries to the
    /// translation table for `locale`. Existing entries
    /// for that locale are overwritten (last-write-wins).
    pub fn add_messages(&self, locale: &str, entries: &[MessageEntry]) {
        let mut table: HashMap<String, HashMap<String, String>> = self.messages.get();
        let entry_map: &mut HashMap<String, String> = table.entry(locale.to_string()).or_default();
        for (key, value) in entries {
            entry_map.insert((*key).to_string(), (*value).to_string());
        }
        self.messages.set(table);
    }

    /// Removes every entry for `locale`. After this
    /// call, `t(key)` for any key will skip this locale
    /// in its lookup chain.
    pub fn remove_locale(&self, locale: &str) {
        let mut table: HashMap<String, HashMap<String, String>> = self.messages.get();
        table.remove(locale);
        self.messages.set(table);
    }

    /// Removes a single message from a locale. After this
    /// call, `t(key)` for this key in this locale will
    /// fall back to `fallback_locale`.
    pub fn remove_message(&self, locale: &str, key: &str) {
        let mut table: HashMap<String, HashMap<String, String>> = self.messages.get();
        if let Some(entry_map) = table.get_mut(locale) {
            entry_map.remove(key);
        }
        self.messages.set(table);
    }

    /// Translates `key` to a string under the active
    /// locale, falling back to `fallback_locale` if the
    /// active locale has no entry. Returns `key` itself
    /// if neither locale has an entry (debug-friendly).
    ///
    /// This is the reactive read — calling it inside a
    /// render closure subscribes that closure to locale
    /// changes (and to any subsequent edits to the
    /// messages map for the active or fallback locale).
    pub fn t(&self, key: &str) -> String {
        let active: String = self.locale.get();
        let fallback: String = self.fallback_locale.get();
        let table: HashMap<String, HashMap<String, String>> = self.messages.get();
        if let Some(message) = table
            .get(&active)
            .and_then(|m: &HashMap<String, String>| m.get(key))
        {
            return message.clone();
        }
        if let Some(message) = table
            .get(&fallback)
            .and_then(|m: &HashMap<String, String>| m.get(key))
        {
            return message.clone();
        }
        key.to_string()
    }

    /// Translates `key` and substitutes `{name}`-style
    /// placeholders from `vars`.
    ///
    /// Placeholders that are present in `vars` are
    /// replaced with their corresponding value.
    /// Placeholders that are missing from `vars` are left
    /// as the literal `{name}` token — matching the
    /// i18next default behavior. No escaping is
    /// supported; add it when a real use case shows up.
    pub fn t_with(&self, key: &str, vars: &HashMap<&'static str, &'static str>) -> String {
        let template: String = self.t(key);
        interpolate(&template, vars)
    }

    /// Returns the number of locales currently registered
    /// (i.e. the number of distinct keys in the messages
    /// map's outer level).
    pub fn locale_count(&self) -> usize {
        self.messages.get().len()
    }

    /// Returns the number of messages registered for the
    /// active locale.
    pub fn active_message_count(&self) -> usize {
        let active: String = self.locale.get();
        self.messages
            .get()
            .get(&active)
            .map(|m: &HashMap<String, String>| m.len())
            .unwrap_or(0)
    }
}

/// Substitutes `{name}`-style placeholders in `template`
/// with values from `vars`.
///
/// Placeholder names may contain alphanumerics and
/// underscores. Missing placeholders are left as the
/// literal `{name}` token. No escaping is performed — the
/// literal text `{` in a translation is treated as the
/// start of a placeholder.
pub(crate) fn interpolate(template: &str, vars: &HashMap<&'static str, &'static str>) -> String {
    let mut output: String = String::with_capacity(template.len());
    let mut chars: std::str::Chars<'_> = template.chars();
    while let Some(c) = chars.next() {
        if c != '{' {
            output.push(c);
            continue;
        }
        // Try to read until the matching `}`. If we
        // hit EOF or another `{` before `}`, treat
        // the `{` as a literal.
        let mut name: String = String::new();
        let mut closed: bool = false;
        for inner in chars.by_ref() {
            if inner == '}' {
                closed = true;
                break;
            }
            name.push(inner);
        }
        if !closed {
            // Unterminated `{` — emit literally.
            output.push('{');
            output.push_str(&name);
            continue;
        }
        // Look up the placeholder.
        match vars.get(name.as_str()) {
            Some(value) => output.push_str(value),
            None => {
                // Leave as literal `{name}` so the
                // missing-translation bug is visible.
                output.push('{');
                output.push_str(&name);
                output.push('}');
            }
        }
    }
    output
}
